[project]
name = "mega-zap"
version = "0.1.0"
description = "Published maps extension for Zap ⚡️"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.44.1",
    "streamlit-sortables>=0.3.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
    "watchdog>=6.0.0",
]
